service: sed-api-auth

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  stage: ${self:provider.stage}
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  stackName: ${self:custom.stage}-${self:service.name}
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    DB: ${env:DB}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-sed-api-gateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-sed-api-gateway-restApiRootResourceId

functions:
  authorize:
    handler: Authorize.handler
  register:
    handler: Register.handler
    events:
      - http:
          path: register
          method: post
          cors: true
  login:
    handler: Login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  me:
    handler: Me.handler
    events:
      - http:
          path: me
          method: get
          cors: true
          authorizer: authorize