service: sed-api-user

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${self:provider.stage}
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  stackName: ${self:custom.stage}-${self:service.name}
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    DB: ${env:DB}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-sed-api-gateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-sed-api-gateway-restApiRootResourceId

functions:
  GetUsers:
    handler: Users.get
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer:
            arn: ${cf:${self:custom.stage}-sed-api-auth.AuthorizeLambdaFunctionQualifiedArn}